# Gunakan image dasar dari Nginx
FROM nginx:latest

# Setel direktori kerja
WORKDIR /usr/share/nginx/html

# Salin semua file HTML ke direktori kerja
COPY . .

# Expose port 80
EXPOSE 80

# Perintah untuk menjalankan Nginx
CMD ["nginx", "-g", "daemon off;"]
